server:
  port: 8094
spring:
  application:
    name: hystrix
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8091/eureka, http://eureka2:8092/eureka

ribbon:
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream