server:
  port: 8097
spring:
  application:
    name: turbine
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8091/eureka, http://eureka2:8092/eureka
turbine:
  app-config: user
  cluster-name-expression: new String("default")